#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="31488_cembscom")]
public partial class helperDataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertBlog_Comment(Blog_Comment instance);
  partial void UpdateBlog_Comment(Blog_Comment instance);
  partial void DeleteBlog_Comment(Blog_Comment instance);
  partial void Inserttbl_quote(tbl_quote instance);
  partial void Updatetbl_quote(tbl_quote instance);
  partial void Deletetbl_quote(tbl_quote instance);
  partial void Insertuser(user instance);
  partial void Updateuser(user instance);
  partial void Deleteuser(user instance);
  partial void InsertCategory(Category instance);
  partial void UpdateCategory(Category instance);
  partial void DeleteCategory(Category instance);
  partial void InsertSearchEngine(SearchEngine instance);
  partial void UpdateSearchEngine(SearchEngine instance);
  partial void DeleteSearchEngine(SearchEngine instance);
  partial void InsertJobAdmin(JobAdmin instance);
  partial void UpdateJobAdmin(JobAdmin instance);
  partial void DeleteJobAdmin(JobAdmin instance);
  partial void InsertJobOpening(JobOpening instance);
  partial void UpdateJobOpening(JobOpening instance);
  partial void DeleteJobOpening(JobOpening instance);
  partial void InsertJobCategory(JobCategory instance);
  partial void UpdateJobCategory(JobCategory instance);
  partial void DeleteJobCategory(JobCategory instance);
  partial void InsertBlog_Post(Blog_Post instance);
  partial void UpdateBlog_Post(Blog_Post instance);
  partial void DeleteBlog_Post(Blog_Post instance);
  partial void InsertProfile(Profile instance);
  partial void UpdateProfile(Profile instance);
  partial void DeleteProfile(Profile instance);
  #endregion
	
	public helperDataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["_31488_cembscomConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public helperDataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public helperDataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public helperDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public helperDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Blog_Comment> Blog_Comments
	{
		get
		{
			return this.GetTable<Blog_Comment>();
		}
	}
	
	public System.Data.Linq.Table<tbl_contact_request> tbl_contact_requests
	{
		get
		{
			return this.GetTable<tbl_contact_request>();
		}
	}
	
	public System.Data.Linq.Table<tbl_quote> tbl_quotes
	{
		get
		{
			return this.GetTable<tbl_quote>();
		}
	}
	
	public System.Data.Linq.Table<user> users
	{
		get
		{
			return this.GetTable<user>();
		}
	}
	
	public System.Data.Linq.Table<Category> Categories
	{
		get
		{
			return this.GetTable<Category>();
		}
	}
	
	public System.Data.Linq.Table<view_Category> view_Categories
	{
		get
		{
			return this.GetTable<view_Category>();
		}
	}
	
	public System.Data.Linq.Table<SearchEngine> SearchEngines
	{
		get
		{
			return this.GetTable<SearchEngine>();
		}
	}
	
	public System.Data.Linq.Table<JobAdmin> JobAdmins
	{
		get
		{
			return this.GetTable<JobAdmin>();
		}
	}
	
	public System.Data.Linq.Table<JobOpening> JobOpenings
	{
		get
		{
			return this.GetTable<JobOpening>();
		}
	}
	
	public System.Data.Linq.Table<JobCategory> JobCategories
	{
		get
		{
			return this.GetTable<JobCategory>();
		}
	}
	
	public System.Data.Linq.Table<Blog_Post> Blog_Posts
	{
		get
		{
			return this.GetTable<Blog_Post>();
		}
	}
	
	public System.Data.Linq.Table<admin_blog> admin_blogs
	{
		get
		{
			return this.GetTable<admin_blog>();
		}
	}
	
	public System.Data.Linq.Table<Profile> Profiles
	{
		get
		{
			return this.GetTable<Profile>();
		}
	}
	
	public System.Data.Linq.Table<UnofficialMailServer> UnofficialMailServers
	{
		get
		{
			return this.GetTable<UnofficialMailServer>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_ins_post")]
	public int proc_ins_post([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string body, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string author, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string categories)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), title, body, author, categories);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_ins_quote")]
	public int proc_ins_quote([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Customername", DbType="NVarChar(50)")] string customername, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Designation", DbType="NVarChar(50)")] string designation, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Company", DbType="NVarChar(100)")] string company, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contact", DbType="NVarChar(20)")] string contact, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Website", DbType="NVarChar(100)")] string website, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Message", DbType="Text")] string message, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestDate", DbType="DateTime")] System.Nullable<System.DateTime> requestDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FormName", DbType="VarChar(100)")] string formName)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customername, designation, company, contact, website, email, message, requestDate, formName);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_insert_comments")]
	public int proc_insert_comments([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> postid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string visitorname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string comments, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string website)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), postid, visitorname, email, comments, website);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_select_month")]
	public ISingleResult<proc_select_monthResult> proc_select_month([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(8)")] string showdate)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), showdate);
		return ((ISingleResult<proc_select_monthResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_select_year")]
	public ISingleResult<proc_select_yearResult> proc_select_year([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(8)")] string showdate)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), showdate);
		return ((ISingleResult<proc_select_yearResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_ins_contact_request")]
	public int proc_ins_contact_request([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Customername", DbType="NVarChar(50)")] string customername, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Designation", DbType="NVarChar(50)")] string designation, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Company", DbType="NVarChar(100)")] string company, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contact", DbType="Decimal(18,0)")] System.Nullable<decimal> contact, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Message", DbType="Text")] string message, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestDate", DbType="DateTime")] System.Nullable<System.DateTime> requestDate)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customername, designation, company, contact, email, message, requestDate);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_ins_categories")]
	public int proc_ins_categories([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string categories)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categories);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_ins_axrequest")]
	public int proc_ins_axrequest([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Customername", DbType="NVarChar(50)")] string customername, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Designation", DbType="NVarChar(50)")] string designation, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Company", DbType="NVarChar(100)")] string company, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contact", DbType="Decimal(18,0)")] System.Nullable<decimal> contact, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Message", DbType="Text")] string message, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestDate", DbType="DateTime")] System.Nullable<System.DateTime> requestDate)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customername, designation, company, contact, email, message, requestDate);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_display_categories")]
	public ISingleResult<proc_display_categoriesResult> proc_display_categories([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string category)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), category);
		return ((ISingleResult<proc_display_categoriesResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_display_all_categories")]
	public ISingleResult<proc_display_all_categoriesResult> proc_display_all_categories()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<proc_display_all_categoriesResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_create_user")]
	public int proc_create_user([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string designation)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, username, password, designation);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_count_comments_for_postid")]
	public ISingleResult<proc_count_comments_for_postidResult> proc_count_comments_for_postid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
		return ((ISingleResult<proc_count_comments_for_postidResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_count_archives")]
	public ISingleResult<proc_count_archivesResult> proc_count_archives()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<proc_count_archivesResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_search")]
	public ISingleResult<proc_searchResult> proc_search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string keyword)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keyword);
		return ((ISingleResult<proc_searchResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_SelectJobCategory")]
	public ISingleResult<proc_SelectJobCategoryResult> proc_SelectJobCategory()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<proc_SelectJobCategoryResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_SelectJobs_Date")]
	public ISingleResult<proc_SelectJobs_DateResult> proc_SelectJobs_Date([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> startdate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> enddate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string category)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), startdate, enddate, category);
		return ((ISingleResult<proc_SelectJobs_DateResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_insert_profiles")]
	public int proc_insert_profiles([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(100)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Location", DbType="VarChar(50)")] string location, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Experience", DbType="VarChar(10)")] string experience, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(200)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactNumber", DbType="VarChar(22)")] string contactNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProfileURL", DbType="VarChar(100)")] string profileURL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Message", DbType="Text")] string message)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, location, experience, email, contactNumber, profileURL, message);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.proc_ins_eventregistrations")]
	public int proc_ins_eventregistrations([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Customername", DbType="NVarChar(50)")] string customername, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Designation", DbType="NVarChar(50)")] string designation, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Company", DbType="NVarChar(100)")] string company, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contact", DbType="NVarChar(20)")] string contact, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Website", DbType="NVarChar(100)")] string website, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Message", DbType="Text")] string message, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestDate", DbType="DateTime")] System.Nullable<System.DateTime> requestDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FormName", DbType="VarChar(100)")] string formName)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customername, designation, company, contact, website, email, message, requestDate, formName);
		return ((int)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Blog_Comments")]
public partial class Blog_Comment : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Post_ID;
	
	private int _Comment_ID;
	
	private string _visitor_name;
	
	private string _Email;
	
	private string _Comments;
	
	private string _Website;
	
	private System.Nullable<byte> _approval;
	
	private System.Nullable<System.DateTime> _Posted_date;
	
	private EntityRef<Blog_Post> _Blog_Post;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPost_IDChanging(int value);
    partial void OnPost_IDChanged();
    partial void OnComment_IDChanging(int value);
    partial void OnComment_IDChanged();
    partial void Onvisitor_nameChanging(string value);
    partial void Onvisitor_nameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    partial void OnWebsiteChanging(string value);
    partial void OnWebsiteChanged();
    partial void OnapprovalChanging(System.Nullable<byte> value);
    partial void OnapprovalChanged();
    partial void OnPosted_dateChanging(System.Nullable<System.DateTime> value);
    partial void OnPosted_dateChanged();
    #endregion
	
	public Blog_Comment()
	{
		this._Blog_Post = default(EntityRef<Blog_Post>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_ID", DbType="Int NOT NULL")]
	public int Post_ID
	{
		get
		{
			return this._Post_ID;
		}
		set
		{
			if ((this._Post_ID != value))
			{
				if (this._Blog_Post.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnPost_IDChanging(value);
				this.SendPropertyChanging();
				this._Post_ID = value;
				this.SendPropertyChanged("Post_ID");
				this.OnPost_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Comment_ID
	{
		get
		{
			return this._Comment_ID;
		}
		set
		{
			if ((this._Comment_ID != value))
			{
				this.OnComment_IDChanging(value);
				this.SendPropertyChanging();
				this._Comment_ID = value;
				this.SendPropertyChanged("Comment_ID");
				this.OnComment_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visitor_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string visitor_name
	{
		get
		{
			return this._visitor_name;
		}
		set
		{
			if ((this._visitor_name != value))
			{
				this.Onvisitor_nameChanging(value);
				this.SendPropertyChanging();
				this._visitor_name = value;
				this.SendPropertyChanged("visitor_name");
				this.Onvisitor_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Comments
	{
		get
		{
			return this._Comments;
		}
		set
		{
			if ((this._Comments != value))
			{
				this.OnCommentsChanging(value);
				this.SendPropertyChanging();
				this._Comments = value;
				this.SendPropertyChanged("Comments");
				this.OnCommentsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="VarChar(50)")]
	public string Website
	{
		get
		{
			return this._Website;
		}
		set
		{
			if ((this._Website != value))
			{
				this.OnWebsiteChanging(value);
				this.SendPropertyChanging();
				this._Website = value;
				this.SendPropertyChanged("Website");
				this.OnWebsiteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_approval", DbType="TinyInt")]
	public System.Nullable<byte> approval
	{
		get
		{
			return this._approval;
		}
		set
		{
			if ((this._approval != value))
			{
				this.OnapprovalChanging(value);
				this.SendPropertyChanging();
				this._approval = value;
				this.SendPropertyChanged("approval");
				this.OnapprovalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Posted_date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Posted_date
	{
		get
		{
			return this._Posted_date;
		}
		set
		{
			if ((this._Posted_date != value))
			{
				this.OnPosted_dateChanging(value);
				this.SendPropertyChanging();
				this._Posted_date = value;
				this.SendPropertyChanged("Posted_date");
				this.OnPosted_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Blog_Post_Blog_Comment", Storage="_Blog_Post", ThisKey="Post_ID", OtherKey="Post_ID", IsForeignKey=true)]
	public Blog_Post Blog_Post
	{
		get
		{
			return this._Blog_Post.Entity;
		}
		set
		{
			Blog_Post previousValue = this._Blog_Post.Entity;
			if (((previousValue != value) 
						|| (this._Blog_Post.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Blog_Post.Entity = null;
					previousValue.Blog_Comments.Remove(this);
				}
				this._Blog_Post.Entity = value;
				if ((value != null))
				{
					value.Blog_Comments.Add(this);
					this._Post_ID = value.Post_ID;
				}
				else
				{
					this._Post_ID = default(int);
				}
				this.SendPropertyChanged("Blog_Post");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_contact_request")]
public partial class tbl_contact_request
{
	
	private int _CustomerID;
	
	private string _Customername;
	
	private string _Designation;
	
	private string _Company;
	
	private decimal _Contact;
	
	private string _Email;
	
	private string _Message;
	
	private System.Nullable<System.DateTime> _RequestDate;
	
	public tbl_contact_request()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int CustomerID
	{
		get
		{
			return this._CustomerID;
		}
		set
		{
			if ((this._CustomerID != value))
			{
				this._CustomerID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customername", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Customername
	{
		get
		{
			return this._Customername;
		}
		set
		{
			if ((this._Customername != value))
			{
				this._Customername = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designation", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Designation
	{
		get
		{
			return this._Designation;
		}
		set
		{
			if ((this._Designation != value))
			{
				this._Designation = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string Company
	{
		get
		{
			return this._Company;
		}
		set
		{
			if ((this._Company != value))
			{
				this._Company = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="Decimal(18,0) NOT NULL")]
	public decimal Contact
	{
		get
		{
			return this._Contact;
		}
		set
		{
			if ((this._Contact != value))
			{
				this._Contact = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this._Email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Message
	{
		get
		{
			return this._Message;
		}
		set
		{
			if ((this._Message != value))
			{
				this._Message = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> RequestDate
	{
		get
		{
			return this._RequestDate;
		}
		set
		{
			if ((this._RequestDate != value))
			{
				this._RequestDate = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_quote")]
public partial class tbl_quote : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _CustomerID;
	
	private string _Customername;
	
	private string _Designation;
	
	private string _Company;
	
	private string _Contact;
	
	private string _Website;
	
	private string _Email;
	
	private string _Message;
	
	private System.Nullable<System.DateTime> _RequestDate;
	
	private string _FormName;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomerIDChanging(int value);
    partial void OnCustomerIDChanged();
    partial void OnCustomernameChanging(string value);
    partial void OnCustomernameChanged();
    partial void OnDesignationChanging(string value);
    partial void OnDesignationChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnWebsiteChanging(string value);
    partial void OnWebsiteChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnRequestDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRequestDateChanged();
    partial void OnFormNameChanging(string value);
    partial void OnFormNameChanged();
    #endregion
	
	public tbl_quote()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int CustomerID
	{
		get
		{
			return this._CustomerID;
		}
		set
		{
			if ((this._CustomerID != value))
			{
				this.OnCustomerIDChanging(value);
				this.SendPropertyChanging();
				this._CustomerID = value;
				this.SendPropertyChanged("CustomerID");
				this.OnCustomerIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customername", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Customername
	{
		get
		{
			return this._Customername;
		}
		set
		{
			if ((this._Customername != value))
			{
				this.OnCustomernameChanging(value);
				this.SendPropertyChanging();
				this._Customername = value;
				this.SendPropertyChanged("Customername");
				this.OnCustomernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designation", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Designation
	{
		get
		{
			return this._Designation;
		}
		set
		{
			if ((this._Designation != value))
			{
				this.OnDesignationChanging(value);
				this.SendPropertyChanging();
				this._Designation = value;
				this.SendPropertyChanged("Designation");
				this.OnDesignationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string Company
	{
		get
		{
			return this._Company;
		}
		set
		{
			if ((this._Company != value))
			{
				this.OnCompanyChanging(value);
				this.SendPropertyChanging();
				this._Company = value;
				this.SendPropertyChanged("Company");
				this.OnCompanyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string Contact
	{
		get
		{
			return this._Contact;
		}
		set
		{
			if ((this._Contact != value))
			{
				this.OnContactChanging(value);
				this.SendPropertyChanging();
				this._Contact = value;
				this.SendPropertyChanged("Contact");
				this.OnContactChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="NVarChar(100)")]
	public string Website
	{
		get
		{
			return this._Website;
		}
		set
		{
			if ((this._Website != value))
			{
				this.OnWebsiteChanging(value);
				this.SendPropertyChanging();
				this._Website = value;
				this.SendPropertyChanged("Website");
				this.OnWebsiteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Message
	{
		get
		{
			return this._Message;
		}
		set
		{
			if ((this._Message != value))
			{
				this.OnMessageChanging(value);
				this.SendPropertyChanging();
				this._Message = value;
				this.SendPropertyChanged("Message");
				this.OnMessageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> RequestDate
	{
		get
		{
			return this._RequestDate;
		}
		set
		{
			if ((this._RequestDate != value))
			{
				this.OnRequestDateChanging(value);
				this.SendPropertyChanging();
				this._RequestDate = value;
				this.SendPropertyChanged("RequestDate");
				this.OnRequestDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string FormName
	{
		get
		{
			return this._FormName;
		}
		set
		{
			if ((this._FormName != value))
			{
				this.OnFormNameChanging(value);
				this.SendPropertyChanging();
				this._FormName = value;
				this.SendPropertyChanged("FormName");
				this.OnFormNameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _name;
	
	private string _username;
	
	private string _password;
	
	private string _designation;
	
	private System.Nullable<int> _status;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OndesignationChanging(string value);
    partial void OndesignationChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    #endregion
	
	public user()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this.OnusernameChanging(value);
				this.SendPropertyChanging();
				this._username = value;
				this.SendPropertyChanged("username");
				this.OnusernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_designation", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string designation
	{
		get
		{
			return this._designation;
		}
		set
		{
			if ((this._designation != value))
			{
				this.OndesignationChanging(value);
				this.SendPropertyChanging();
				this._designation = value;
				this.SendPropertyChanged("designation");
				this.OndesignationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
	public System.Nullable<int> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categories")]
public partial class Category : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _category_id;
	
	private string _categories;
	
	private string _location;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncategory_idChanging(int value);
    partial void Oncategory_idChanged();
    partial void OncategoriesChanging(string value);
    partial void OncategoriesChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    #endregion
	
	public Category()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int category_id
	{
		get
		{
			return this._category_id;
		}
		set
		{
			if ((this._category_id != value))
			{
				this.Oncategory_idChanging(value);
				this.SendPropertyChanging();
				this._category_id = value;
				this.SendPropertyChanged("category_id");
				this.Oncategory_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categories", DbType="VarChar(50)")]
	public string categories
	{
		get
		{
			return this._categories;
		}
		set
		{
			if ((this._categories != value))
			{
				this.OncategoriesChanging(value);
				this.SendPropertyChanging();
				this._categories = value;
				this.SendPropertyChanged("categories");
				this.OncategoriesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="NVarChar(100)")]
	public string location
	{
		get
		{
			return this._location;
		}
		set
		{
			if ((this._location != value))
			{
				this.OnlocationChanging(value);
				this.SendPropertyChanging();
				this._location = value;
				this.SendPropertyChanged("location");
				this.OnlocationChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.view_Category")]
public partial class view_Category
{
	
	private string _Categories;
	
	private int _Post_ID;
	
	public view_Category()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categories", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Categories
	{
		get
		{
			return this._Categories;
		}
		set
		{
			if ((this._Categories != value))
			{
				this._Categories = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int Post_ID
	{
		get
		{
			return this._Post_ID;
		}
		set
		{
			if ((this._Post_ID != value))
			{
				this._Post_ID = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SearchEngine")]
public partial class SearchEngine : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _searchID;
	
	private string _page_title;
	
	private string _page_url;
	
	private string _page_content;
	
	private string _keywords;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsearchIDChanging(string value);
    partial void OnsearchIDChanged();
    partial void Onpage_titleChanging(string value);
    partial void Onpage_titleChanged();
    partial void Onpage_urlChanging(string value);
    partial void Onpage_urlChanged();
    partial void Onpage_contentChanging(string value);
    partial void Onpage_contentChanged();
    partial void OnkeywordsChanging(string value);
    partial void OnkeywordsChanged();
    #endregion
	
	public SearchEngine()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchID", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string searchID
	{
		get
		{
			return this._searchID;
		}
		set
		{
			if ((this._searchID != value))
			{
				this.OnsearchIDChanging(value);
				this.SendPropertyChanging();
				this._searchID = value;
				this.SendPropertyChanged("searchID");
				this.OnsearchIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_title", DbType="VarChar(200)")]
	public string page_title
	{
		get
		{
			return this._page_title;
		}
		set
		{
			if ((this._page_title != value))
			{
				this.Onpage_titleChanging(value);
				this.SendPropertyChanging();
				this._page_title = value;
				this.SendPropertyChanged("page_title");
				this.Onpage_titleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_url", DbType="NVarChar(200)")]
	public string page_url
	{
		get
		{
			return this._page_url;
		}
		set
		{
			if ((this._page_url != value))
			{
				this.Onpage_urlChanging(value);
				this.SendPropertyChanging();
				this._page_url = value;
				this.SendPropertyChanged("page_url");
				this.Onpage_urlChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_content", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string page_content
	{
		get
		{
			return this._page_content;
		}
		set
		{
			if ((this._page_content != value))
			{
				this.Onpage_contentChanging(value);
				this.SendPropertyChanging();
				this._page_content = value;
				this.SendPropertyChanged("page_content");
				this.Onpage_contentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keywords", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string keywords
	{
		get
		{
			return this._keywords;
		}
		set
		{
			if ((this._keywords != value))
			{
				this.OnkeywordsChanging(value);
				this.SendPropertyChanging();
				this._keywords = value;
				this.SendPropertyChanged("keywords");
				this.OnkeywordsChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JobAdmin")]
public partial class JobAdmin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _JobAdminID;
	
	private string _JobAdmin1;
	
	private string _JobPassword;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJobAdminIDChanging(int value);
    partial void OnJobAdminIDChanged();
    partial void OnJobAdmin1Changing(string value);
    partial void OnJobAdmin1Changed();
    partial void OnJobPasswordChanging(string value);
    partial void OnJobPasswordChanged();
    #endregion
	
	public JobAdmin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobAdminID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int JobAdminID
	{
		get
		{
			return this._JobAdminID;
		}
		set
		{
			if ((this._JobAdminID != value))
			{
				this.OnJobAdminIDChanging(value);
				this.SendPropertyChanging();
				this._JobAdminID = value;
				this.SendPropertyChanged("JobAdminID");
				this.OnJobAdminIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="JobAdmin", Storage="_JobAdmin1", DbType="VarChar(50)")]
	public string JobAdmin1
	{
		get
		{
			return this._JobAdmin1;
		}
		set
		{
			if ((this._JobAdmin1 != value))
			{
				this.OnJobAdmin1Changing(value);
				this.SendPropertyChanging();
				this._JobAdmin1 = value;
				this.SendPropertyChanged("JobAdmin1");
				this.OnJobAdmin1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobPassword", DbType="VarChar(50)")]
	public string JobPassword
	{
		get
		{
			return this._JobPassword;
		}
		set
		{
			if ((this._JobPassword != value))
			{
				this.OnJobPasswordChanging(value);
				this.SendPropertyChanging();
				this._JobPassword = value;
				this.SendPropertyChanged("JobPassword");
				this.OnJobPasswordChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JobOpenings")]
public partial class JobOpening : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _JobID;
	
	private string _Category;
	
	private string _JobTitle;
	
	private string _Skills;
	
	private string _Location;
	
	private System.Nullable<int> _MinimumExperience;
	
	private System.Nullable<int> _MaximumExperience;
	
	private string _CareerLevel;
	
	private string _JD;
	
	private System.Nullable<System.DateTime> _PostedDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJobIDChanging(int value);
    partial void OnJobIDChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnJobTitleChanging(string value);
    partial void OnJobTitleChanged();
    partial void OnSkillsChanging(string value);
    partial void OnSkillsChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnMinimumExperienceChanging(System.Nullable<int> value);
    partial void OnMinimumExperienceChanged();
    partial void OnMaximumExperienceChanging(System.Nullable<int> value);
    partial void OnMaximumExperienceChanged();
    partial void OnCareerLevelChanging(string value);
    partial void OnCareerLevelChanged();
    partial void OnJDChanging(string value);
    partial void OnJDChanged();
    partial void OnPostedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPostedDateChanged();
    #endregion
	
	public JobOpening()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int JobID
	{
		get
		{
			return this._JobID;
		}
		set
		{
			if ((this._JobID != value))
			{
				this.OnJobIDChanging(value);
				this.SendPropertyChanging();
				this._JobID = value;
				this.SendPropertyChanged("JobID");
				this.OnJobIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(100)")]
	public string Category
	{
		get
		{
			return this._Category;
		}
		set
		{
			if ((this._Category != value))
			{
				this.OnCategoryChanging(value);
				this.SendPropertyChanging();
				this._Category = value;
				this.SendPropertyChanged("Category");
				this.OnCategoryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitle", DbType="VarChar(100)")]
	public string JobTitle
	{
		get
		{
			return this._JobTitle;
		}
		set
		{
			if ((this._JobTitle != value))
			{
				this.OnJobTitleChanging(value);
				this.SendPropertyChanging();
				this._JobTitle = value;
				this.SendPropertyChanged("JobTitle");
				this.OnJobTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Skills", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Skills
	{
		get
		{
			return this._Skills;
		}
		set
		{
			if ((this._Skills != value))
			{
				this.OnSkillsChanging(value);
				this.SendPropertyChanging();
				this._Skills = value;
				this.SendPropertyChanged("Skills");
				this.OnSkillsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(50)")]
	public string Location
	{
		get
		{
			return this._Location;
		}
		set
		{
			if ((this._Location != value))
			{
				this.OnLocationChanging(value);
				this.SendPropertyChanging();
				this._Location = value;
				this.SendPropertyChanged("Location");
				this.OnLocationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinimumExperience", DbType="Int")]
	public System.Nullable<int> MinimumExperience
	{
		get
		{
			return this._MinimumExperience;
		}
		set
		{
			if ((this._MinimumExperience != value))
			{
				this.OnMinimumExperienceChanging(value);
				this.SendPropertyChanging();
				this._MinimumExperience = value;
				this.SendPropertyChanged("MinimumExperience");
				this.OnMinimumExperienceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaximumExperience", DbType="Int")]
	public System.Nullable<int> MaximumExperience
	{
		get
		{
			return this._MaximumExperience;
		}
		set
		{
			if ((this._MaximumExperience != value))
			{
				this.OnMaximumExperienceChanging(value);
				this.SendPropertyChanging();
				this._MaximumExperience = value;
				this.SendPropertyChanged("MaximumExperience");
				this.OnMaximumExperienceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CareerLevel", DbType="VarChar(50)")]
	public string CareerLevel
	{
		get
		{
			return this._CareerLevel;
		}
		set
		{
			if ((this._CareerLevel != value))
			{
				this.OnCareerLevelChanging(value);
				this.SendPropertyChanging();
				this._CareerLevel = value;
				this.SendPropertyChanged("CareerLevel");
				this.OnCareerLevelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JD", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string JD
	{
		get
		{
			return this._JD;
		}
		set
		{
			if ((this._JD != value))
			{
				this.OnJDChanging(value);
				this.SendPropertyChanging();
				this._JD = value;
				this.SendPropertyChanged("JD");
				this.OnJDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostedDate", DbType="SmallDateTime")]
	public System.Nullable<System.DateTime> PostedDate
	{
		get
		{
			return this._PostedDate;
		}
		set
		{
			if ((this._PostedDate != value))
			{
				this.OnPostedDateChanging(value);
				this.SendPropertyChanging();
				this._PostedDate = value;
				this.SendPropertyChanged("PostedDate");
				this.OnPostedDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JobCategories")]
public partial class JobCategory : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _JobCategory1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnJobCategory1Changing(string value);
    partial void OnJobCategory1Changed();
    #endregion
	
	public JobCategory()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="JobCategory", Storage="_JobCategory1", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string JobCategory1
	{
		get
		{
			return this._JobCategory1;
		}
		set
		{
			if ((this._JobCategory1 != value))
			{
				this.OnJobCategory1Changing(value);
				this.SendPropertyChanging();
				this._JobCategory1 = value;
				this.SendPropertyChanged("JobCategory1");
				this.OnJobCategory1Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Blog_Post")]
public partial class Blog_Post : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Post_ID;
	
	private string _Title;
	
	private string _Body;
	
	private string _BodyPath;
	
	private System.Nullable<System.DateTime> _Posted_date;
	
	private string _Author;
	
	private string _Posted_Month;
	
	private System.Nullable<int> _Posted_Year;
	
	private string _Categories;
	
	private string _Archives;
	
	private string _ImageSRC;
	
	private EntitySet<Blog_Comment> _Blog_Comments;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPost_IDChanging(int value);
    partial void OnPost_IDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnBodyChanging(string value);
    partial void OnBodyChanged();
    partial void OnBodyPathChanging(string value);
    partial void OnBodyPathChanged();
    partial void OnPosted_dateChanging(System.Nullable<System.DateTime> value);
    partial void OnPosted_dateChanged();
    partial void OnAuthorChanging(string value);
    partial void OnAuthorChanged();
    partial void OnPosted_MonthChanging(string value);
    partial void OnPosted_MonthChanged();
    partial void OnPosted_YearChanging(System.Nullable<int> value);
    partial void OnPosted_YearChanged();
    partial void OnCategoriesChanging(string value);
    partial void OnCategoriesChanged();
    partial void OnArchivesChanging(string value);
    partial void OnArchivesChanged();
    partial void OnImageSRCChanging(string value);
    partial void OnImageSRCChanged();
    #endregion
	
	public Blog_Post()
	{
		this._Blog_Comments = new EntitySet<Blog_Comment>(new Action<Blog_Comment>(this.attach_Blog_Comments), new Action<Blog_Comment>(this.detach_Blog_Comments));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Post_ID
	{
		get
		{
			return this._Post_ID;
		}
		set
		{
			if ((this._Post_ID != value))
			{
				this.OnPost_IDChanging(value);
				this.SendPropertyChanging();
				this._Post_ID = value;
				this.SendPropertyChanged("Post_ID");
				this.OnPost_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
	public string Title
	{
		get
		{
			return this._Title;
		}
		set
		{
			if ((this._Title != value))
			{
				this.OnTitleChanging(value);
				this.SendPropertyChanging();
				this._Title = value;
				this.SendPropertyChanged("Title");
				this.OnTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Body", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Body
	{
		get
		{
			return this._Body;
		}
		set
		{
			if ((this._Body != value))
			{
				this.OnBodyChanging(value);
				this.SendPropertyChanging();
				this._Body = value;
				this.SendPropertyChanged("Body");
				this.OnBodyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BodyPath", DbType="VarChar(50)")]
	public string BodyPath
	{
		get
		{
			return this._BodyPath;
		}
		set
		{
			if ((this._BodyPath != value))
			{
				this.OnBodyPathChanging(value);
				this.SendPropertyChanging();
				this._BodyPath = value;
				this.SendPropertyChanged("BodyPath");
				this.OnBodyPathChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Posted_date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Posted_date
	{
		get
		{
			return this._Posted_date;
		}
		set
		{
			if ((this._Posted_date != value))
			{
				this.OnPosted_dateChanging(value);
				this.SendPropertyChanging();
				this._Posted_date = value;
				this.SendPropertyChanged("Posted_date");
				this.OnPosted_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Author", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Author
	{
		get
		{
			return this._Author;
		}
		set
		{
			if ((this._Author != value))
			{
				this.OnAuthorChanging(value);
				this.SendPropertyChanging();
				this._Author = value;
				this.SendPropertyChanged("Author");
				this.OnAuthorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Posted_Month", DbType="VarChar(10)")]
	public string Posted_Month
	{
		get
		{
			return this._Posted_Month;
		}
		set
		{
			if ((this._Posted_Month != value))
			{
				this.OnPosted_MonthChanging(value);
				this.SendPropertyChanging();
				this._Posted_Month = value;
				this.SendPropertyChanged("Posted_Month");
				this.OnPosted_MonthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Posted_Year", DbType="Int")]
	public System.Nullable<int> Posted_Year
	{
		get
		{
			return this._Posted_Year;
		}
		set
		{
			if ((this._Posted_Year != value))
			{
				this.OnPosted_YearChanging(value);
				this.SendPropertyChanging();
				this._Posted_Year = value;
				this.SendPropertyChanged("Posted_Year");
				this.OnPosted_YearChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categories", DbType="NVarChar(50)")]
	public string Categories
	{
		get
		{
			return this._Categories;
		}
		set
		{
			if ((this._Categories != value))
			{
				this.OnCategoriesChanging(value);
				this.SendPropertyChanging();
				this._Categories = value;
				this.SendPropertyChanged("Categories");
				this.OnCategoriesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Archives", DbType="VarChar(10)")]
	public string Archives
	{
		get
		{
			return this._Archives;
		}
		set
		{
			if ((this._Archives != value))
			{
				this.OnArchivesChanging(value);
				this.SendPropertyChanging();
				this._Archives = value;
				this.SendPropertyChanged("Archives");
				this.OnArchivesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageSRC", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string ImageSRC
	{
		get
		{
			return this._ImageSRC;
		}
		set
		{
			if ((this._ImageSRC != value))
			{
				this.OnImageSRCChanging(value);
				this.SendPropertyChanging();
				this._ImageSRC = value;
				this.SendPropertyChanged("ImageSRC");
				this.OnImageSRCChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Blog_Post_Blog_Comment", Storage="_Blog_Comments", ThisKey="Post_ID", OtherKey="Post_ID")]
	public EntitySet<Blog_Comment> Blog_Comments
	{
		get
		{
			return this._Blog_Comments;
		}
		set
		{
			this._Blog_Comments.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Blog_Comments(Blog_Comment entity)
	{
		this.SendPropertyChanging();
		entity.Blog_Post = this;
	}
	
	private void detach_Blog_Comments(Blog_Comment entity)
	{
		this.SendPropertyChanging();
		entity.Blog_Post = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin_blog")]
public partial class admin_blog
{
	
	private string _admin_name;
	
	private string _admin_password;
	
	private System.Nullable<int> _admin_status;
	
	public admin_blog()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_name", DbType="NVarChar(50)")]
	public string admin_name
	{
		get
		{
			return this._admin_name;
		}
		set
		{
			if ((this._admin_name != value))
			{
				this._admin_name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_password", DbType="NVarChar(50)")]
	public string admin_password
	{
		get
		{
			return this._admin_password;
		}
		set
		{
			if ((this._admin_password != value))
			{
				this._admin_password = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_status", DbType="Int")]
	public System.Nullable<int> admin_status
	{
		get
		{
			return this._admin_status;
		}
		set
		{
			if ((this._admin_status != value))
			{
				this._admin_status = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Profiles")]
public partial class Profile : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Name;
	
	private string _Location;
	
	private string _Experience;
	
	private string _Email;
	
	private string _ContactNumber;
	
	private string _Message;
	
	private string _ProfileURL;
	
	private System.Nullable<System.DateTime> _AppliedDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnExperienceChanging(string value);
    partial void OnExperienceChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnContactNumberChanging(string value);
    partial void OnContactNumberChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnProfileURLChanging(string value);
    partial void OnProfileURLChanged();
    partial void OnAppliedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnAppliedDateChanged();
    #endregion
	
	public Profile()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(50)")]
	public string Location
	{
		get
		{
			return this._Location;
		}
		set
		{
			if ((this._Location != value))
			{
				this.OnLocationChanging(value);
				this.SendPropertyChanging();
				this._Location = value;
				this.SendPropertyChanged("Location");
				this.OnLocationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Experience", DbType="VarChar(10)")]
	public string Experience
	{
		get
		{
			return this._Experience;
		}
		set
		{
			if ((this._Experience != value))
			{
				this.OnExperienceChanging(value);
				this.SendPropertyChanging();
				this._Experience = value;
				this.SendPropertyChanged("Experience");
				this.OnExperienceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNumber", DbType="VarChar(22)")]
	public string ContactNumber
	{
		get
		{
			return this._ContactNumber;
		}
		set
		{
			if ((this._ContactNumber != value))
			{
				this.OnContactNumberChanging(value);
				this.SendPropertyChanging();
				this._ContactNumber = value;
				this.SendPropertyChanged("ContactNumber");
				this.OnContactNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Message
	{
		get
		{
			return this._Message;
		}
		set
		{
			if ((this._Message != value))
			{
				this.OnMessageChanging(value);
				this.SendPropertyChanging();
				this._Message = value;
				this.SendPropertyChanged("Message");
				this.OnMessageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfileURL", DbType="VarChar(100)")]
	public string ProfileURL
	{
		get
		{
			return this._ProfileURL;
		}
		set
		{
			if ((this._ProfileURL != value))
			{
				this.OnProfileURLChanging(value);
				this.SendPropertyChanging();
				this._ProfileURL = value;
				this.SendPropertyChanged("ProfileURL");
				this.OnProfileURLChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppliedDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> AppliedDate
	{
		get
		{
			return this._AppliedDate;
		}
		set
		{
			if ((this._AppliedDate != value))
			{
				this.OnAppliedDateChanging(value);
				this.SendPropertyChanging();
				this._AppliedDate = value;
				this.SendPropertyChanged("AppliedDate");
				this.OnAppliedDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UnofficialMailServers")]
public partial class UnofficialMailServer
{
	
	private string _domains;
	
	public UnofficialMailServer()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_domains", DbType="NVarChar(255)")]
	public string domains
	{
		get
		{
			return this._domains;
		}
		set
		{
			if ((this._domains != value))
			{
				this._domains = value;
			}
		}
	}
}

public partial class proc_select_monthResult
{
	
	private System.Nullable<int> _Column1;
	
	public proc_select_monthResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
	public System.Nullable<int> Column1
	{
		get
		{
			return this._Column1;
		}
		set
		{
			if ((this._Column1 != value))
			{
				this._Column1 = value;
			}
		}
	}
}

public partial class proc_select_yearResult
{
	
	private System.Nullable<int> _Column1;
	
	public proc_select_yearResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
	public System.Nullable<int> Column1
	{
		get
		{
			return this._Column1;
		}
		set
		{
			if ((this._Column1 != value))
			{
				this._Column1 = value;
			}
		}
	}
}

public partial class proc_display_categoriesResult
{
	
	private int _category_id;
	
	private string _categories;
	
	private string _location;
	
	public proc_display_categoriesResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", DbType="Int NOT NULL")]
	public int category_id
	{
		get
		{
			return this._category_id;
		}
		set
		{
			if ((this._category_id != value))
			{
				this._category_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categories", DbType="VarChar(50)")]
	public string categories
	{
		get
		{
			return this._categories;
		}
		set
		{
			if ((this._categories != value))
			{
				this._categories = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="NVarChar(100)")]
	public string location
	{
		get
		{
			return this._location;
		}
		set
		{
			if ((this._location != value))
			{
				this._location = value;
			}
		}
	}
}

public partial class proc_display_all_categoriesResult
{
	
	private int _category_id;
	
	private string _categories;
	
	private string _location;
	
	public proc_display_all_categoriesResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", DbType="Int NOT NULL")]
	public int category_id
	{
		get
		{
			return this._category_id;
		}
		set
		{
			if ((this._category_id != value))
			{
				this._category_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categories", DbType="VarChar(50)")]
	public string categories
	{
		get
		{
			return this._categories;
		}
		set
		{
			if ((this._categories != value))
			{
				this._categories = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="NVarChar(100)")]
	public string location
	{
		get
		{
			return this._location;
		}
		set
		{
			if ((this._location != value))
			{
				this._location = value;
			}
		}
	}
}

public partial class proc_count_comments_for_postidResult
{
	
	private int _Post_ID;
	
	private string _Author;
	
	private string _Comments;
	
	public proc_count_comments_for_postidResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Post_ID", DbType="Int NOT NULL")]
	public int Post_ID
	{
		get
		{
			return this._Post_ID;
		}
		set
		{
			if ((this._Post_ID != value))
			{
				this._Post_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Author", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Author
	{
		get
		{
			return this._Author;
		}
		set
		{
			if ((this._Author != value))
			{
				this._Author = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Comments
	{
		get
		{
			return this._Comments;
		}
		set
		{
			if ((this._Comments != value))
			{
				this._Comments = value;
			}
		}
	}
}

public partial class proc_count_archivesResult
{
	
	private System.Nullable<int> _rcount;
	
	private string _Archives;
	
	public proc_count_archivesResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rcount", DbType="Int")]
	public System.Nullable<int> rcount
	{
		get
		{
			return this._rcount;
		}
		set
		{
			if ((this._rcount != value))
			{
				this._rcount = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Archives", DbType="VarChar(10)")]
	public string Archives
	{
		get
		{
			return this._Archives;
		}
		set
		{
			if ((this._Archives != value))
			{
				this._Archives = value;
			}
		}
	}
}

public partial class proc_searchResult
{
	
	private string _searchID;
	
	private string _page_title;
	
	private string _page_url;
	
	private string _page_content;
	
	private string _keywords;
	
	public proc_searchResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_searchID", DbType="NChar(10) NOT NULL", CanBeNull=false)]
	public string searchID
	{
		get
		{
			return this._searchID;
		}
		set
		{
			if ((this._searchID != value))
			{
				this._searchID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_title", DbType="VarChar(200)")]
	public string page_title
	{
		get
		{
			return this._page_title;
		}
		set
		{
			if ((this._page_title != value))
			{
				this._page_title = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_url", DbType="NVarChar(200)")]
	public string page_url
	{
		get
		{
			return this._page_url;
		}
		set
		{
			if ((this._page_url != value))
			{
				this._page_url = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_content", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string page_content
	{
		get
		{
			return this._page_content;
		}
		set
		{
			if ((this._page_content != value))
			{
				this._page_content = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keywords", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string keywords
	{
		get
		{
			return this._keywords;
		}
		set
		{
			if ((this._keywords != value))
			{
				this._keywords = value;
			}
		}
	}
}

public partial class proc_SelectJobCategoryResult
{
	
	private string _JobCategory;
	
	public proc_SelectJobCategoryResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobCategory", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string JobCategory
	{
		get
		{
			return this._JobCategory;
		}
		set
		{
			if ((this._JobCategory != value))
			{
				this._JobCategory = value;
			}
		}
	}
}

public partial class proc_SelectJobs_DateResult
{
	
	private int _JobID;
	
	private string _Category;
	
	private string _JobTitle;
	
	private string _Skills;
	
	private string _Location;
	
	private System.Nullable<int> _MinimumExperience;
	
	private System.Nullable<int> _MaximumExperience;
	
	private string _CareerLevel;
	
	private string _JD;
	
	private System.Nullable<System.DateTime> _PostedDate;
	
	public proc_SelectJobs_DateResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobID", DbType="Int NOT NULL")]
	public int JobID
	{
		get
		{
			return this._JobID;
		}
		set
		{
			if ((this._JobID != value))
			{
				this._JobID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(100)")]
	public string Category
	{
		get
		{
			return this._Category;
		}
		set
		{
			if ((this._Category != value))
			{
				this._Category = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitle", DbType="VarChar(100)")]
	public string JobTitle
	{
		get
		{
			return this._JobTitle;
		}
		set
		{
			if ((this._JobTitle != value))
			{
				this._JobTitle = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Skills", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Skills
	{
		get
		{
			return this._Skills;
		}
		set
		{
			if ((this._Skills != value))
			{
				this._Skills = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(50)")]
	public string Location
	{
		get
		{
			return this._Location;
		}
		set
		{
			if ((this._Location != value))
			{
				this._Location = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinimumExperience", DbType="Int")]
	public System.Nullable<int> MinimumExperience
	{
		get
		{
			return this._MinimumExperience;
		}
		set
		{
			if ((this._MinimumExperience != value))
			{
				this._MinimumExperience = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaximumExperience", DbType="Int")]
	public System.Nullable<int> MaximumExperience
	{
		get
		{
			return this._MaximumExperience;
		}
		set
		{
			if ((this._MaximumExperience != value))
			{
				this._MaximumExperience = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CareerLevel", DbType="VarChar(50)")]
	public string CareerLevel
	{
		get
		{
			return this._CareerLevel;
		}
		set
		{
			if ((this._CareerLevel != value))
			{
				this._CareerLevel = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JD", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string JD
	{
		get
		{
			return this._JD;
		}
		set
		{
			if ((this._JD != value))
			{
				this._JD = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostedDate", DbType="Date")]
	public System.Nullable<System.DateTime> PostedDate
	{
		get
		{
			return this._PostedDate;
		}
		set
		{
			if ((this._PostedDate != value))
			{
				this._PostedDate = value;
			}
		}
	}
}
#pragma warning restore 1591
