document.write("<h1>Equipment Rental <\/h2>");
document.write("<p>The success of an organization in an  equipment rental industry ultimately depends on its owner’s ability to react to  the client’s needs. Either you rent or maintain vehicles, machinery or  equipment; you need a complete end-to-end suite of solution that will be  capable of handling your complete business process, provide timely and valuable  business information and connecting you with your clients while providing  visibility across the dealership. Additionally the solution must meet the demands of the changing new market  trends, adapting to the new technology changes, intricate operations management  because of larger vehicle fleets and machinery outfits, and an ever-changing  range of customer needs in the market. <br \/>");
document.write("  CEM’s  solution for Equipment rental industry is a modern, fully integrated ERP  solution that combines the advantages of Microsoft Dynamics ERP technology with  our industry expertise customized modules. CEM offers a broad range of features  that supports major rental process for equipment, automotive and heavy  machinery companies. From years of knowledge and experience drawn from working  with rental companies, CEM provides an end-to-end solution that can easily  handle your complete business process and adapt to the ever-changing market  trends. <br \/>");
document.write("  <strong>FEATURES<\/strong><\/p>");
document.write("<ul class=\"ul_reasons\">");
document.write("  <li>Manage Equipment Purchase &amp; Hiring  (External and Internal hiring)<\/li>");
document.write("  <li>Trade agreements for both internal &amp;  external hire <\/li>");
document.write("  <li>Integration of PMV with fixed assets module <\/li>");
document.write("  <li>Maintain &amp; track equipment log sheet <\/li>");
document.write("  <li>Equipment transfer history <\/li>");
document.write("  <li>Equipment hire renewal with history <\/li>");
document.write("  <li>Track fuel consumption <\/li>");
document.write("  <li>Manage mobilization\/demobilization costs of  equipment hire<\/li>");
document.write("  <li>Regular alerts for equipment related documents  including registration, license, Security pass, warranty period expiration,  etc.<\/li>");
document.write("<\/ul>");
document.write("<p>Benefits:<\/p>");
document.write("<ul class=\"ul_reasons\">");
document.write("  <li>All key business processes are       mapped in a single legacy system<\/li>");
document.write("  <li>Manage Bulk and individual equipment       rental or purchase<\/li>");
document.write("  <li>Fully integrated financial       accounting<\/li>");
document.write("  <li>Multilingual and multicurrency       support across your entire organization<\/li>");
document.write("  <li>Scalable and customizable<\/li>");
document.write("  <li>Reliable, user-friendly       solution<\/li>");
document.write("<\/ul>");
