document.write('<h1>Logistics and Distribution</h1>');
document.write("<p>The Logistics business is fast-growing and dynamic. Managing Supply Chain is difficult under ideal conditions. But conditions are rarely ideal. When economies begin to falter, when consumer demand starts to fall off, and fuel prices begin to rise, companies in the Logistics and Distribution must respond immediately. Companies need to provide on-time delivery, proper tracking, user-friendly customer service and 24\/7 availability.<\/p>");
document.write("<p>CEM's ERP transportation solutions improve data access and reporting strength and provide perfect visibility into the business process. Fully integrated with Microsoft Dynamics Technology, CEM's Logistics ERP solution is scalable, flexible and easily configurable to meet the unique needs of Logistics and Distribution organizations. It is ideal for transporters, logistics providers, truck loaders, freight forwarders, multinational and multi-model freight forwarders, and for providers managing warehouse and logistics services. Our rich experience in implementation of Logistics Management solution has provided:<\/p>");
document.write("<ul class=\"ul_reasons\">");
document.write("<li>Visibility across the enterprise<\/li>");
document.write("<li>Efficient workflow<\/li>");
document.write("<li>Faster communication to all stakeholders<\/li>");
document.write("<li>More accurate and faster transactions<\/li>");
document.write("<li>Increased reliability and lowered costs<\/li>");
document.write("<li>Improved functionality of IT teams to be more productive with less involvement from consultants<\/li>");
document.write("<li>Improved customer service<\/li>");
document.write("<\/ul>");
