document.write('<h1>Microsoft Dynamics for Manufacturers </h1>');
document.write("<p></p>");
document.write("<p>Success in the manufacturing industry depends largely on the organization's ability to adapt to changing client requirements. This usually entails changing intricate, complex processes almost instantly and still turning a profit. Add government regulatory standards, union compliance and bank financing to the equation and the complexity of manufacturing gets ratcheted-up even further.<\/p>");
document.write("<p>CEM's extensive knowledge and experience in the manufacturing industry can help manufacturers adapt to the business' idiosyncrasies and market changes. Based on Microsoft Dynamics ERP\/CRM technology and over a decade of experience in the Manufacturing industry, our solutions hold the key to stay on top of the competition and reduce the factors that inflate costs and lower product quality. CEM's Dynamics AX for Manufacturing for example, automates financial, customer relationship, supply-chain management, which in turn, reduces inventory and production costs, increases productivity and improves visibility into operations. Some of the benefits of CEM Dynamics for Manufacturing are:<\/p>");
document.write("<ul class=\"ul_reasons\">");
document.write("<li>Improves control over business processes and supports the organization with a purpose-built technology structure<\/li>");
document.write("<li>Enhances operations and improves efficiency of the entire organization with a unified operation resource model<\/li>");
document.write("<li>Gains immediate insight and boosts productivity with RoleTailored user experiences<\/li>");
document.write("<li>Responds to changing conditions, corrects capacity imbalances, and tracks sustainability<\/li>");
document.write("<li>Adapts to changing process and regulatory requirements with Manufacturing Industry's model-driven methodology<\/li>");
document.write("<li>Enhances collaboration and communication between employees, customers, suppliers, and partners<\/li>");
document.write("<\/ul>");
document.write("<p><strong>Lean Manufacturing<\/strong><\/p>");
document.write("<p>Maintaining efficient operations in today's manufacturing environment isn't easy, but putting into practice the principles of lean manufacturing can further hone your organization's competitive edge. Typical manufacturing plants have multiple vendors, multiple interfaces, complex information flows, and asynchronous processing, all of which can lead to limited visibility into orders, materials, and production. To achieve peak performance in the process of manufacturing, manufacturers must systematically identify and eliminate plant floor inefficiencies.<\/p>");
document.write("<p><strong>This Lean Manufacturing strategy requires a four-step cycle of continuous improvement:<\/strong><\/p>");
document.write("<ul class=\"ul_reasons\">");
document.write("<li>Value stream mapping, documents each step in the process, its inputs and outputs, across the entire supply chain<\/li>");
document.write("<li>Analysis and modeling identify tasks that could be simplified or cut altogether<\/li>");
document.write("<li>Implementation and continuous improvement actualizes change on the plant floor<\/li>");
document.write("<li>Management and reporting evaluates the results and begins the cycle again<\/li>");
document.write("<\/ul>");
