document.write("<h1>Microsoft Dynamics for Oil &amp; Gas Industry<\/h1>");
document.write("<p></p>");
document.write("<p>Project-based businesses working in the Oil and Gas industry have a unique set of challenges before them. Project failure in this industry can usually be traced to a lack of expertise in managing various business processes critical to the project. In short, whenever a business with its many moving parts, lacks a rock-solid process in place, one small error can bring the whole operation down. Working with one software solution for accounting, another for project management and another for customer relationships is a recipe for disaster. When these functions work independently, there are just too many opportunities for important details to fall through the cracks. CEM's solutions for the Oil &amp; Gas Industry provide end-to-end solutions where all major operations are interlinked, with dashboard controls to give management a real time assessment of the business. This way, decisions can be made based on facts, rather than conjecture.<\/p>");
document.write("<p>Some of the benefits of CEM's Oil &amp; Gas solutions are:<\/p>");
document.write("<ul class=\"ul_reasons\">");
document.write("<li>Management and control of workforce, materials and equipment in real-time<\/li>");
document.write("<li>Management of assets from procurement to invoicing, through the respective modules<\/li>");
document.write("<li>Real-time reporting and budget tracking capabilities that improve the efficiency of management and management decision making<\/li>");
document.write("<li>Visibility into project costs and revenues<\/li>");
document.write("<li>Automation of project billing to avoid discrepancies during invoicing and accounts payable<\/li>");
document.write("<li>Boosted efficiency with Microsoft Dynamics technology to improve business operations<\/li>");
document.write("<li>Flexibility and ease-of-use with any Microsoft associated program<\/li>");
document.write("<\/ul>");
