document.write('<h1>Microsoft Dynamics for the Retail Industry</h1>');
document.write("<p></p>");
document.write("<p>Challenged by online Direct-To-Market channels, traditional brick &amp; mortar retailers have fought back with technology as their biggest weapon. Technology has paved the way to optimize inventory management, improve logistics, manage finance and cash flow, all while delivering a superior customer experience.<\/p>");
document.write("<p>CEM understands these trends and challenges and provides a complete set of retail solutions from Microsoft Dynamics to improve visibility across the entire network of retail outlets. CEM implements a retail ERP system on top of Microsoft Dynamics ERP technology that automates much of the day-to-day process, while providing management with a top-down view of all operations for strategic planning.<\/p>");
document.write("<p><strong>Merchandising<\/strong> &mdash; Provides real-time customer insight that can deliver new and relevant customer experiences<\/p>");
document.write("<ul class=\"ul_reasons\">");
document.write("<li>Speed the purchase decision<\/li>");
document.write("<li>Predict customer needs and react to the new market opportunities<\/li>");
document.write("<li>Audit all plans and revisions<\/li>");
document.write("<li>Automate pricing actions to take advantage of market and competitive conditions<\/li>");
document.write("<li>Enhance profit margins from promotion to clearance<\/li>");
document.write("<li>Improve customer service by understanding customer requirements<\/li>");
document.write("<li>Reduce data errors with one set of master plans<\/li>");
document.write("<\/ul>");
document.write("<p><strong>Marketing<\/strong> &mdash; Increase customer loyalty and business margins.<\/p>");
document.write("<ul class=\"ul_reasons\">");
document.write("<li>Effectively execute all promotional activities across various okutlets and channels<\/li>");
document.write("<li>Optimize product price levels and enhance sales and profit margins<\/li>");
document.write("<li>Track expenses and profitability during the product promotional activities<\/li>");
document.write("<li>Enhance customer loyalty and provide a differentiated customer shopping experience<\/li>");
document.write("<li>Organize and monitor customer-focused marketing events<\/li>");
document.write("<li>Identify the most effective promotions<\/li>");
document.write("<li>Increase loyalty with service offerings that deliver longer term value<\/li>");
document.write("<\/ul>");
document.write("<p><strong>Supply Chain <\/strong>&mdash; Optimize inventory levels with integrated planning and execution.<\/p>");
document.write("<ul class=\"ul_reasons\">");
document.write("<li>Advanced service level, lessened stock-outs<\/li>");
document.write("<li>Cut down inventory levels, enhance turns<\/li>");
document.write("<li>Increase profit margin by apportioning the products based on store\/channel demand<\/li>");
document.write("<li>Cut down lost sales and gain shopper loyalty by sourcing the product from the most trusted vendors<\/li>");
document.write("<li>Automate regulatory compliance with customs tariffs and government regulations<\/li>");
document.write("<li>Minimize supply chain costs and improve in-stock position<\/li>");
document.write("<li>Align operations with a strategy to provide end-to-end process transparency and visibility<\/li>");
document.write("<li>Improve employee flexibility, reduce labor costs<\/li>");
document.write("<li>Increase utilization of resources<\/li>");
document.write("<\/ul>");
document.write("<p><strong>Store and Channel Operations<\/strong> &mdash; Increase profit margins and customer satisfaction.<\/p>");
document.write("<ul class=\"ul_reasons\">");
document.write("<li>Match the increasing needs of staff and customers by enhancing sales and service<\/li>");
document.write("<li>Create confidence among employees by informing them of Best Practices in retil management<\/li>");
document.write("<li>Create personal and targeted shopping experiences<\/li>");
document.write("<li>Manage regulatory compliance<\/li>");
document.write("<li>Improve services and increase customer satisfaction<\/li>");
document.write("<li>Optimize business processes through fast and flexible request handling, high system availability, and optimal use of user-interface performance<\/li>");
document.write("<\/ul>");
document.write("<p><strong>IT<\/strong> &mdash; Standardize information with integrated and simplified business processes to transform the retail enterprise via the latest technology advances.<\/p>");
document.write("<ul class=\"ul_reasons\">");
document.write("<li>Adapt quickly to the changing business requirements<\/li>");
document.write("<li>Scale solutions as the business grows<\/li>");
document.write("<li>Deploy flexible and operational options across multiple geographies and locations<\/li>");
document.write("<li>Includes Object Linking and Embedding for Point of Sale (OPOS), to enhance your point of sale (POS) hardware and peripheral choice<\/li>");
document.write("<li>Manage PCI data security standards compliance and on-going support<\/li>");
document.write("<\/ul>");
