document.write("<ul class=\"tabs\">");
document.write("                <li><a href=\"#construction\">Construction<\/a><\/li>");
document.write("                <li><a href=\"#contracting\">Contracting<\/a><\/li>                ");
document.write("                <li><a href=\"#projects\">Projects<\/a><\/li>");
document.write("                <li><a href=\"#service\">Professional services<\/a><\/li>");
document.write("                <li><a href=\"#oil\">Oil &amp; Gas<\/a><\/li>");
document.write("                <li><a href=\"#manufacturing\">Manufacturing<\/a><\/li>");
document.write("                <li><a href=\"#trading\">Trading<\/a><\/li>");
document.write("                <li><a href=\"#logistics\">Logistics/Distribution<\/a><\/li>");
document.write("                <li><a href=\"#retail\">Retail<\/a><\/li>");
document.write("                <li><a href=\"#group\">Group companies<\/a><\/li>");
document.write("            <\/ul>");
document.write("            <div class=\"tab_container\">");
document.write("                <div id=\"industry\" class=\"tab_content\">");
document.write("                    <script type=\"text\/javascript\" src=\"Industries_content_js\/industry.js\"><\/script>");
document.write("                <\/div>");
document.write("                <div id=\"construction\" class=\"tab_content\">");
document.write("                    <script type=\"text\/javascript\" src=\"Industries_content_js\/construction.js\"><\/script>");
document.write("                <\/div>");
document.write("                <div id=\"contracting\" class=\"tab_content\">");
document.write("                    <script type=\"text\/javascript\" src=\"Industries_content_js\/contracting.js\"><\/script>");
document.write("                <\/div>");
document.write("                <div id=\"projects\" class=\"tab_content\">");
document.write("                    <script type=\"text\/javascript\" src=\"Industries_content_js\/projects.js\"><\/script>");
document.write("                <\/div>");
document.write("                <div id=\"service\" class=\"tab_content\">");
document.write("                    <script src=\"Industries_content_js\/serviceindustries.js\" type=\"text\/javascript\"><\/script>");
document.write("                <\/div>");
document.write("                <div id=\"oil\" class=\"tab_content\">");
document.write("                    <script src=\"Industries_content_js\/oil.js\" type=\"text\/javascript\"><\/script>");
document.write("                <\/div>");
document.write("                <div id=\"manufacturing\" class=\"tab_content\">");
document.write("                    <script src=\"Industries_content_js\/manufacturing.js\" type=\"text\/javascript\"><\/script>");
document.write("                <\/div>");
document.write("                <div id=\"trading\" class=\"tab_content\">");
document.write("                    <script src=\"Industries_content_js\/trading.js\" type=\"text\/javascript\"><\/script>");
document.write("                <\/div>");
document.write("                <div id=\"logistics\" class=\"tab_content\">");
document.write("                    <script src=\"Industries_content_js\/logistics.js\" type=\"text\/javascript\"><\/script>");
document.write("                <\/div>");
document.write("                <div id=\"retail\" class=\"tab_content\">");
document.write("                    <script type=\"text\/javascript\" src=\"Industries_content_js\/retail.js\"><\/script>");
document.write("                <\/div>");
document.write("                <div id=\"group\" class=\"tab_content\">");
document.write("                    <script type=\"text\/javascript\" src=\"Industries_content_js\/group.js\"><\/script>");
document.write("                <\/div>");
document.write("            <\/div>");