document.write("<h1>Microsoft Dynamics for the Trading Industry<\/h1>");
document.write("<p>The rise of huge consumer markets in China and India, coupled with global communications that can create demand anywhere, any time, and advanced logistics technologies have all contributed to make the Trading Industry more lucrative than ever before. Of course, that makes the Trading Industry more competitive than ever before as well. Information is the key to success, and that starts with a robust, technically sound, ERP system. To meet this need, Microsoft Dynamics provides state of the art ERP software, and CEM provides the add-on modules to customize and enhance capabilities for individual clients in the Trading Industry.<\/p>");
document.write("<p>CEM offers a powerful, adaptable and fully integrated solution for the Trading Industry that gives companies' the ability to manage every aspect of their business process. From order entry to shipment delivery, all integral parts of your business are covered with CEM trading software. From technical and functional viewpoint, CEM's trading solutions supports multi-market requirements and international business activities including tax and legal demands.<\/p>");
document.write("<p><strong>Streamline Business Operations<\/strong><\/p>");
document.write("<ul class=\"ul_reasons\">");
document.write("<li>Automate critical business processes from order entry to shipment delivery, and help reduce unnecessary activities<\/li>");
document.write("<li>Deliver real-time business intelligence and alerts on the status of the business to management and customers<\/li>");
document.write("<li>Enable customer self-service through Web portals<\/li>");
document.write("<\/ul>");
document.write("<p><strong>Improve Supply Chain and Inventory Management<\/strong><\/p>");
document.write("<ul class=\"ul_reasons\">");
document.write("<li>Provide easy, real-time visibility into inventory, sales, purchasing and financial information across multiple locations<\/li>");
document.write("<li>Accurately track shipping and delivery of parts by integrating Automatic Data Collection (ADC) functionality with Enterprise Resource Planning (ERP)<\/li>");
document.write("<li>Maintain accurate real-time inventory data and optimize layout, picking methods and movement<\/li>");
document.write("<li>Create accurate demand forecasts<\/li>");
document.write("<\/ul>");
document.write("<p><strong>Enhance Customer Relationships<\/strong><\/p>");
document.write("<ul class=\"ul_reasons\">");
document.write("<li>Help ensure accurate and on-time delivery with powerful customer\/supplier integration, planning tools and company-wide inventory visibility<\/li>");
document.write("<li>Respond rapidly to unique customer demands such as specific packaging and shipping requirements<\/li>");
document.write("<li>Manage customer interactions across multiple communication channels<\/li>");
document.write("<\/ul>");
